config/routes.rb
Rails.application.routes.draw do
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    resources :cars, only: %i(index create)
    resources :makers, only: %i(index)
    resources :car_models, only: %i(show)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :maker
  belongs_to :car_model
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :maker
end

app/models/maker.rb
class Maker < ApplicationRecord
end

app/controllers/api/car_models_controller.rb
class Api::CarModelsController < ApplicationController
  def show
    @car_models = CarModel.where(maker_id: params[:id])
    render 'show', formats: 'json', handlers: 'jbuilder'
  end
end

app/controllers/api/cars_controller.rb
class Api::CarsController < ApiController
  def index
    @cars = Car.all
    render 'index', formats: 'json', handlers: 'jbuilder'
  end

  def create
    @car = Car.create(car_params)
  end

  private
    def car_params
      params.require(:car).permit(:maker_id, :maker_name, :car_model_id, :car_model_name, :price)
    end
end

app/controllers/api/makers_controller.rb
class Api::MakersController < ApplicationController
  def index
    @makers = Maker.all
    render 'index', formats: 'json', handlers: 'jbuilder'
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:maker_id, :maker_name, :car_model_id, :car_model_name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :maker_id %>
    <%= form.text_field :maker_id, id: :car_maker_id %>
  </div>

  <div class="field">
    <%= form.label :maker_name %>
    <%= form.text_field :maker_name, id: :car_maker_name %>
  </div>

  <div class="field">
    <%= form.label :car_model_id %>
    <%= form.text_field :car_model_id, id: :car_car_model_id %>
  </div>

  <div class="field">
    <%= form.label :car_model_name %>
    <%= form.text_field :car_model_name, id: :car_car_model_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :car_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Maker</th>
      <th>Maker name</th>
      <th>Car model</th>
      <th>Car model name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.maker %></td>
        <td><%= car.maker_name %></td>
        <td><%= car.car_model %></td>
        <td><%= car.car_model_name %></td>
        <td><%= car.price %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<div id="car_form">
  <router-view></router-view>
</div>

<%= javascript_pack_tag 'cars/new' %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Maker:</strong>
  <%= @car.maker %>
</p>

<p>
  <strong>Maker name:</strong>
  <%= @car.maker_name %>
</p>

<p>
  <strong>Car model:</strong>
  <%= @car.car_model %>
</p>

<p>
  <strong>Car model name:</strong>
  <%= @car.car_model_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VueSample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="nav">
      <div class="nav-left">
        <span class="nav-item">
          <span class="fa fa-language"></span>車両管理
        </span>
      </div>
    </header>
    <div class="hero is-info is-bold">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">RailsとVue</h1>
          <h2 class="subtitle">vue-routerによるルーティング / vuexによるstate管理</h2>
        </div>
      </div>
    </div>
    <main class="columns">
      <div class="column" >
        <div class="box media" >
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>